namespace FLTK.NET;

public enum Key : int
{
    None = FLTKNative.Fl_Key.Fl_Key_None,
    Button = FLTKNative.Fl_Key.Fl_Key_Button,
    BackSpace = FLTKNative.Fl_Key.Fl_Key_BackSpace,
    Tab = FLTKNative.Fl_Key.Fl_Key_Tab,
    IsoKey = FLTKNative.Fl_Key.Fl_Key_IsoKey,
    Enter = FLTKNative.Fl_Key.Fl_Key_Enter,
    Pause = FLTKNative.Fl_Key.Fl_Key_Pause,
    ScrollLock = FLTKNative.Fl_Key.Fl_Key_ScrollLock,
    Escape = FLTKNative.Fl_Key.Fl_Key_Escape,
    Kana = FLTKNative.Fl_Key.Fl_Key_Kana,
    Eisu = FLTKNative.Fl_Key.Fl_Key_Eisu,
    Yen = FLTKNative.Fl_Key.Fl_Key_Yen,
    JISUnderscore = FLTKNative.Fl_Key.Fl_Key_JISUnderscore,
    Home = FLTKNative.Fl_Key.Fl_Key_Home,
    Left = FLTKNative.Fl_Key.Fl_Key_Left,
    Up = FLTKNative.Fl_Key.Fl_Key_Up,
    Right = FLTKNative.Fl_Key.Fl_Key_Right,
    Down = FLTKNative.Fl_Key.Fl_Key_Down,
    PageUp = FLTKNative.Fl_Key.Fl_Key_PageUp,
    PageDown = FLTKNative.Fl_Key.Fl_Key_PageDown,
    End = FLTKNative.Fl_Key.Fl_Key_End,
    Print = FLTKNative.Fl_Key.Fl_Key_Print,
    Insert = FLTKNative.Fl_Key.Fl_Key_Insert,
    Menu = FLTKNative.Fl_Key.Fl_Key_Menu,
    Help = FLTKNative.Fl_Key.Fl_Key_Help,
    NumLock = FLTKNative.Fl_Key.Fl_Key_NumLock,
    KP = FLTKNative.Fl_Key.Fl_Key_KP,
    KPEnter = FLTKNative.Fl_Key.Fl_Key_KPEnter,
    KPLast = FLTKNative.Fl_Key.Fl_Key_KPLast,
    F1 = FLTKNative.Fl_Key.Fl_Key_F1,
    F2 = FLTKNative.Fl_Key.Fl_Key_F2,
    F3 = FLTKNative.Fl_Key.Fl_Key_F3,
    F4 = FLTKNative.Fl_Key.Fl_Key_F4,
    F5 = FLTKNative.Fl_Key.Fl_Key_F5,
    F6 = FLTKNative.Fl_Key.Fl_Key_F6,
    F7 = FLTKNative.Fl_Key.Fl_Key_F7,
    F8 = FLTKNative.Fl_Key.Fl_Key_F8,
    F9 = FLTKNative.Fl_Key.Fl_Key_F9,
    F10 = FLTKNative.Fl_Key.Fl_Key_F10,
    F11 = FLTKNative.Fl_Key.Fl_Key_F11,
    F12 = FLTKNative.Fl_Key.Fl_Key_F12,
    FLast = FLTKNative.Fl_Key.Fl_Key_FLast,
    ShiftL = FLTKNative.Fl_Key.Fl_Key_ShiftL,
    ShiftR = FLTKNative.Fl_Key.Fl_Key_ShiftR,
    ControlL = FLTKNative.Fl_Key.Fl_Key_ControlL,
    ControlR = FLTKNative.Fl_Key.Fl_Key_ControlR,
    CapsLock = FLTKNative.Fl_Key.Fl_Key_CapsLock,
    MetaL = FLTKNative.Fl_Key.Fl_Key_MetaL,
    MetaR = FLTKNative.Fl_Key.Fl_Key_MetaR,
    AltL = FLTKNative.Fl_Key.Fl_Key_AltL,
    AltR = FLTKNative.Fl_Key.Fl_Key_AltR,
    Delete = FLTKNative.Fl_Key.Fl_Key_Delete,
}